CREATE TABLE IF NOT EXISTS competition_tracks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    short_description TEXT,
    full_description LONGTEXT,
    category ENUM('research', 'poster', 'innovation', 'case', 'oral', 'other') DEFAULT 'research',
    eligibility TEXT,
    rules LONGTEXT,
    judging_criteria LONGTEXT,
    prizes TEXT,
    submission_deadline DATETIME,
    max_participants INT,
    registration_fee DECIMAL(10,2),
    display_order INT DEFAULT 0,
    featured BOOLEAN DEFAULT FALSE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
